#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义


#数据库配置
spring:
  datasource:
    url: jdbc:mysql://124.71.219.89/adventure
    username: root
    password: qq2845166476
    driver-class-name: com.mysql.cj.jdbc.Driver
# 重定向
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*


#deepseek大模型配置
deepseek:
  api:
    key: sk-4b4087e8793b48bf995860db5711d1fa
    base-url: https://api.deepseek.com